# Generated by Django 3.2.14 on 2023-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhapi', '0037_alter_abstract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='main_author',
            field=models.BooleanField(default=False),
        ),
    ]
