name: Build and publish latest Docker image
on:
  # Trigger the workflow on push or pull request,
  # for the develop branch and all new tags
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "RELEASE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Extract commit hash
        shell: bash
        run: echo "RELEASE_REVISION=$(git rev-parse --short ${GITHUB_SHA})" >> $GITHUB_ENV
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          GIT_BRANCH: ${{ env.RELEASE_BRANCH }}
          GIT_REVISION: ${{ env.RELEASE_REVISION }}
          GIT_TAG: latest
        with:
          name: c2dhunilu/journal-of-digital-history-backend
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildargs: GIT_BRANCH,GIT_REVISION,GIT_TAG
          tags: 'latest'
